name: My first workflow
on: 
  push:
    branches: 
      - 'v[0-9]+.[0-9]'
jobs:
  hello_world:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    steps:    
  
    - name: Checkout sourse
      uses: actions/checkout@v2
    
    - name: Build_DockerfileImage
      run: |
        docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
        
    - name: Install_Cosign
      uses: sigstore/cosign-installer@v3.1.2

    - name: Setup_QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Setup_Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login_Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: zhangshi0131/zhangshi0131:${{github.sha}}
          
    - name: Check Docs File
      run: |
        mkdir -p docs
        
    - name: Run_Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'table'
        scan-type: 'fs'
        output: 'trivy_scan_results.txt'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Move
      if: ${{ failure() }} 
      run: mv trivy_scan_results.txt docs/
  
   #If success    
    - name: Sign image with a key
      if: ${{ success() }} 
      run: |
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
      env:
        TAGS: zhangshi0131/zhangshi0131:${{github.sha}}
        COSIGN_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}

        
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }} 
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: |
          Name:Zhang Shi
          Metriculation:A0286008A
          Email:e1221820@u.nus.edu
          Git:${{ secrets.GIT }}
          Image:${{ secrets.IMAGE }}
        SLACK_TITLE: Image Build and Sign
        SLACK_USERNAME: CICD
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

    #If failure
    - uses: MeilCli/slack-upload-file@v3
      if: ${{ failure() }} 
      with:
          slack_token: ${{ secrets.SlACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL }}
          content: table
          
          file_path: 'docs/trivy_scan_results.txt'
          title: 'table'
          initial_comment: 'post by slack-upload-file'
