name: My first workflow
on: 
  push:
    branches: 
      -'v[0-9]+.[0-9]'
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Echo current branch
      run: echo "$(date):Current branch is ${{ github.ref_name}}"
      
    - name: Checkout sourse
      uses: actions/checkout@v2

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.12.0
            
      
