name: My first workflow
on: 
  push:
    branches: 
      - 'v[0-9]+.[0-9]'
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:          
    - name: Checkout sourse
      uses: actions/checkout@v2

    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
        
    - name: Run_Trivy_vulnerability_scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
