name: My first workflow
on: 
  push:
    branches: 
      -'v[0-9]+.[0-9]'
jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Echo current branch
      run: echo "$(date):Current branch is ${{ github.ref_name}}"
      
    - name: Checkout sourse
      uses: actions/checkout@v2

    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@0.12.0
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
            
      
